### ISSUE TITLE
[todo] synchronize the html in Zhu's webpage

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/crystallography#21]

**Comment by qzhu2017** [comment]
http://www.physics.unlv.edu/~qzhu/code/html/index.html

**Comment by scottfredericks** [comment]
@qzhu2017 
I can access the link. However, if I click on one of the [source] links in the module documentation, I get the following type of error:
"Forbidden

You don't have permission to access /~qzhu/code/html/_modules/crystallography/molecule.html on this server."

**Comment by qzhu2017** [comment]
It is fixed now.
