### ISSUE TITLE
lattice assignment

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/crystallography#5]
Sometimes the program fails due to very unbalance lattice assignment.
Li8 Ca4 O10
1.0
101.924633 0.000000 0.000000
2.092458 1.699747 0.000000
0.901087 1.611128 1.139483
Ca Li O
4 8 10
direct
0.618499 0.026280 0.781551 Ca
0.381501 0.973720 0.218449 Ca
0.934161 0.947708 0.208905 Ca
0.065839 0.052292 0.791095 Ca
0.699432 0.589616 0.423058 Li
0.300568 0.410384 0.576942 Li
0.276588 0.174145 0.497114 Li
0.723412 0.825855 0.502886 Li
0.165347 0.126766 0.852747 Li
0.834653 0.873234 0.147253 Li
0.893754 0.494705 0.883722 Li
0.106246 0.505295 0.116278 Li
0.980766 0.937745 0.976306 O
0.019234 0.062255 0.023694 O
0.543600 0.986248 0.909981 O
0.456400 0.013752 0.090019 O
0.699099 0.094702 0.612930 O
0.300901 0.905298 0.387070 O
0.481797 0.128817 0.121688 O
0.518203 0.871183 0.878312 O
0.468908 0.946897 0.805108 O
0.531092 0.053103 0.194892 O

**Comment by scottfredericks** [comment]
Hi Dr. Zhu,

Can you please tell me the conditions under which the generate_lattice
function failed?

On Apr 19, 2018 1:22 PM, "Qiang Zhu" <notifications@github.com> wrote:

@scottfredericks <https://github.com/scottfredericks> the improvement on
8313764
<https://github.com/qzhu2017/crystallography/commit/83137642166c28df55321b5e07d1ddfa4ba019d4>
sometimes will fail to generate the certified lattice after a number of
attempts. Needs to prevent this failure.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/qzhu2017/crystallography/issues/5#issuecomment-382868700>,
or mute the thread

**Comment by qzhu2017** [comment]
try to run
```
# python test.py 
```
You will quickly find the program stopped at some points due to the failure of lattice generation.

**Comment by scottfredericks** [comment]
I have changed the value of minvec in the generate_lattice function, which
should help when generating small lattices. After that change, test.py
seems to fail mainly for monoclinic and orthorhombic space groups, which
still have unbalanced ratios for a, b, and c. I will change the methods for
those cases to use random 3-vectors.

**Comment by qzhu2017** [comment]
excellent. Please just use test.py to run the test and if you find no problem with lattice generation, please close this issue.

**Comment by scottfredericks** [comment]
I have implemented the random vector method for the remaining lattice types. I have also checked that the resulting lattice constants obey the appropriate statistics. test.py no longer fails to generate lattices.

**Comment by qzhu2017** [comment]
@scottfredericks There is a bug in the lattice assignment. I found sometimes, the generated lattice has a volume not equal to the estimated volume. Here is 
3489dad62bd78c39146e3c0b3a158304bffdc57d

try to run
```
python structure.py -s 22 -e C -n 12 -v 1.0
```
to reproduce this error.

**Comment by scottfredericks** [comment]
I have changed the code to use
`vec = random_vector()
abc = volume/x
xyz = vec[0]*vec[1]*vec[2]
a = vec[0]*np.cbrt(abc)/np.cbrt(xyz)
b = vec[1]*np.cbrt(abc)/np.cbrt(xyz)
c = vec[2]*np.cbrt(abc)/np.cbrt(xyz)`
I think the problem now results from the c vector in para2matrix. If we set
mat1 = random_matrix()
mat2 = para2matrix(matrix2para(mat1))
we get slightly different determinants for mat1 and mat2. I am having difficulty figuring out what the correct formula for the c vector should be.

**Comment by qzhu2017** [comment]
There are multiple ways of transforming from para to matrix. 
Currently, para2matrix function only convert the matrix to lower triangular matrix, while random_matrix returns a symmetric matrix. We need to add an option to para2matrix to output symmetric matrix, which is actually more useful in crystallography.
```python
def para2matrix(cell_para, radians=True, mode='s'):
    """ 
    1x6 (a, b, c, alpha, beta, gamma) -> 3x3 matrix representation  
    Args:
    cell_para: a, b, c, alpha, beta, gamma
    radians: if angle are in radian. True/False
    mode: the form of matrix:  s/l/u
    Return:
    matrix: symmetric/low triangular/upper triangular 3*3 matrix
    """
```
@scottfredericks  This is not very critical now, please finish the option of adding PBC condition first.

**Comment by qzhu2017** [comment]
@scottfredericks There is a bug in matrix2para
```python
    cell_para[5] = angle(matrix[1], matrix[2])
    cell_para[4] = angle(matrix[0], matrix[2])
    cell_para[3] = angle(matrix[0], matrix[1])
```
it should be 
```python
        cell_para[5] = angle(matrix[0], matrix[1]) 
        cell_para[4] = angle(matrix[0], matrix[2])
        cell_para[3] = angle(matrix[1], matrix[2])
```

Could you please double check the two functions of para2matrix and matrix2para?

**Comment by qzhu2017** [comment]
@scottfredericks Please double check these two functions of para2matrix and matrix2para. After that, we can close this issue.

**Comment by scottfredericks** [comment]
I have double-checked the functionality by calling matrix2para on matrices generated from para2matrix. The results seem to be consistent now. Additionally, I have added an option for creating upper-diagonal matrices instead of lower.
